#include <stdio.h>
#include <stdlib.h>

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

typedef struct
{
    int * sequence; // pointer which stores the address of dynamic array
    int length; // length of fibonacci sequence
} fibonacci;


fibonacci create_fibonacci(int num)
{
    /* 
    Creates Fibonacci sequence of numbers up to specified number num.
    Returns fib
    */

   int* sequence = (int*)malloc(2*sizeof(int));
   sequence[0]=1;
   sequence[1]=2;
   int curr_len = 2; // current length of fibonacci sequence

   while ((sequence[curr_len-1] + sequence[curr_len-2]<num))
   {
       // add new element of fibonacci sequence if it is smaller then num
       curr_len += 1;
       sequence = (int*)realloc(sequence, curr_len*sizeof(int));
       sequence[curr_len-1] = sequence[curr_len-2] + sequence[curr_len-3];
   }

   // create resulting fibonacci sequence structure of final array and its length
   fibonacci fib;
   fib.sequence = sequence;
   fib.length = curr_len;

   return fib;
}

int main()
{
    // create fibonacci sequence of numbers up to 4000000
    fibonacci fib = create_fibonacci(4000000);

    /*
    // print resulting fibonacci sequence
    printf("Fibonacci sequence: \n");
    for(int i=0;i<fib.length;i++)
    {
        printf("Element %d: %d\n", i, fib.sequence[i]);
    }
    printf("Length of array: %d\n", fib.length);
    */

    // find sum of the even numbers in the array
    int sum=0;
    for(int i=0;i<fib.length;i++)
    {
        if (!(fib.sequence[i]%2))
        {
            sum += fib.sequence[i];
        }
    }

    printf("Resulting sum is equal to: %d", sum);
    return 0;
}

